workspace:
  base: /go
  path: src/git.exlhub.io/exlinc/golang-utils

pipeline:
  install:
    image: golang:1.9.2
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure -v
  envconfig-test:
    image: golang:1.9.2
    commands:
      - cd envconfig
      - go build
      - go test
