workspace:
  base: /go
  path: src/exlgit.com/golang/utils

pipeline:
  install:
    image: golang:1.9.2
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure -v
  envconfig-test:
    image: golang:1.9.2
    commands:
      - cd envconfig
      - go build
      - go test
  uuid-test:
    image: golang:1.9.2
    commands:
      - cd uuid
      - go build
      - go test
  jsonhttp-build:
    image: golang:1.9.2
    commands:
      - cd jsonhttp
      - go build
  httpredirect-build:
    image: golang:1.9.2
    commands:
      - cd httpredirect
      - go build
  httpcookies-build:
    image: golang:1.9.2
    commands:
      - cd httpcookies
      - go build
  htmlhttp-build:
    image: golang:1.9.2
    commands:
      - cd htmlhttp
      - go build
  httpimages-build:
    image: golang:1.9.2
    commands:
      - cd httpimages
      - go build
  httpmiddleware-build:
    image: golang:1.9.2
    commands:
      - cd httpmiddleware
      - go build
  muxvars-build:
    image: golang:1.9.2
    commands:
      - cd muxvars
      - go build
  queryparams-build:
    image: golang:1.9.2
    commands:
      - cd queryparams
      - go build
  sqlutils-build:
    image: golang:1.9.2
    commands:
      - cd sqlutils
      - go build
